### ISSUE TITLE
Use on my data

### ISSUE THREAD

**Issue by bouachalazhar** [SoccerNet/SoccerNet-v3#2]
Hi ! Can we use SoccerNet-v3 on a single video (.mp4 file) ?

**Comment by SilvioGiancola** [comment]
SoccerNet-v3 refers to a dataset, what do you mean by "using SoccerNet-v3 on a single video"? For each task, we have developed specific development kit per task: https://www.soccer-net.org/tasks

**Comment by bouachalazhar** [comment]
Ok, is it possible to test Camera Shot Segmentation task on my data ?

**Comment by SilvioGiancola** [comment]
Please refer to SoccerNet-v2 for this task: https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task2-CameraShotSegmentation
Yes, you can test Camera Shot Segmentation task on your data.
