### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by pulism** [SoccerNet/SoccerNet-v3#3]
``` python
downloader = SoccerNetDownloader(LocalDirectory="images")
downloader.downloadGames(files=["Labels-v3.json", "Frames-v3.zip"], split=["validation"])
```
Is causing the following error:
```
UnboundLocalError: local variable 'jsonGamesFile' referenced before assignment
```

**Comment by SilvioGiancola** [comment]
Please provide a fully reproducible code for that error. Make sure you have the latest version of the SoccerNet pip package.

**Comment by SilvioGiancola** [comment]
The split name is wrong: https://github.com/SoccerNet/SoccerNet-v3#download-data

Please follow this standard:

```python
from SoccerNet.Downloader import SoccerNetDownloader
mySoccerNetDownloader = SoccerNetDownloader(LocalDirectory="path/to/SoccerNet")
mySoccerNetDownloader.downloadGames(files=["Labels-v3.json", "Frames-v3.zip"], split=["train","valid","test"], task="frames") # download frames and labels for the 400 games of SN v3 - Requires around 60 GB of local storage
```

**Comment by pulism** [comment]
Oh. That worked!

It was my fault, but maybe an error message could be handy here. Not sure how many times this happens though, I could have been the only person who this has happened to so not sure if it's worth the effort.
